### PR TITLE
Update website to use v0.4.0

### PR DESCRIPTION
**Pull request by rfk**
@jedie this updates the website to use v0.4.0 release, can you please check?

### CODE REVIEW

**Comment by rfk** [comment]
Hmm, travis failure, digging in...

**Comment by rfk** [comment]
OK, tests are green now

**Comment by jedie** [comment]
+1

**Comment by rfk** [comment]
thanks :-)

**Comment by jedie** [comment]
With https://github.com/pypyjs/pypyjs-examples/commit/448b671ce5ceed91616765de34047ee9406bd0b7 i update the examples...

**Pull request merged**
