### PR TITLE
Update editor.css

### PR DESCRIPTION
**Pull request by girishramnani**
scrolled down on run. so made the size of the components relative .

### CODE REVIEW

**Comment by jedie** [comment]
Generally a good idea. Thanks for contributing.

But why 55% to 25%, in other words: bigger editor and smaller console...
IMHO the console is a little to small, isn't it?

This brings me to this idea:

```
.CodeMirror, #console {
    height: 25%;
    transition: height 1s ease;
}
.CodeMirror:hover, #console:hover {
    height: 50%;
}
```

With https://github.com/jedie/pypyjs.github.io/commit/af039247ca468bd20c330d3e421bf76bf021fc3f it can be tryout here:
- https://jedie.github.io/pypyjs.github.io/editor.html
- https://jedie.github.io/pypyjs.github.io/json_test.html

Maybe to kittenish?

**Comment by girishramnani** [comment]
usually in editors eg sublime isnt the editor bigger. Also i m using the code of this site on my blog. I didnt find any LICENSE . so would like to ask for permission .

**Comment by girishramnani** [comment]
that looks good.
so closing this pull request.

**Comment by jedie** [comment]
I think https://github.com/jedie/pypyjs.github.io/commit/af039247ca468bd20c330d3e421bf76bf021fc3f can be enhanced:

Made only CodeMirror on **focus** big and in all other cases the console... But i didn't find the CSS combination for this...

**Comment by girishramnani** [comment]
maybe you need to add some js

**Comment by jedie** [comment]
There exists two dynamic CSS classes:
- **.CodeMirror-focused** (If editor has the focus)
- **.jqconsole-blurred** (If console has not the focus)

So, IMHO all is there, to made a only-CSS-solution...

**Comment by girishramnani** [comment]
ok , so first keeping both 35% (as on 25% some of that empty space doesnt really feel good) then when code mirror on focus - increase the size of it and decrease for console. similarly for the console

**Comment by girishramnani** [comment]
thanks. and so should i close this pull request?

**Comment by jedie** [comment]
No, it's not "fixed", yet :-P

> ok , so first keeping both 35% (as on 25% some of that empty space doesnt really feel good) then when code mirror on focus - increase the size of it and decrease for console. similarly for the console 

Can you contribute this?

**Comment by girishramnani** [comment]
trying.

**Comment by girishramnani** [comment]
used these classes

```
.CodeMirror,#console {
    height: 35%;
    transition: height 1s ease;
}

.jqconsole {
     transition: height 1s ease;
}

.CodeMirror-focused {
 height: 50%;       
}
/*70% of the #console*/
.jqconsole-blurred {
 height: 70%;   
}
```

but the transition isnt working for the console.

**Comment by girishramnani** [comment]
I cant find a solution for css only solution. Do you have a suggestion?

**Comment by jedie** [comment]
> I cant find a solution for css only solution. Do you have a suggestion?

No. The problem is IMHO that there is no way to say: console is big, but only if there is no **.CodeMirror-focused**

Think **.jqconsole-blurred** didn't help here...

So some JS is needed, isn't it?

**Comment by jedie** [comment]
OK, this works:

```
    CodeMirrorEditor.on("focus", function() {
        $("#console").css("height", "20%");
        $(".CodeMirror").css("height", "60%");
    });
    CodeMirrorEditor.on("blur", function() {
        $("#console").css("height", "60%");
        $(".CodeMirror").css("height", "20%");
    });
```

But i think the values should be in CSS instead of JS... So, i will look to add only a .css class by JS...

**Comment by jedie** [comment]
> But i think the values should be in CSS instead of JS... So, i will look to add only a .css class by JS...

done here: https://github.com/jedie/pypyjs.github.io/commit/c615ece65e1f54ce3c3fba5aef28f2201284bcc4
-   https://jedie.github.io/pypyjs.github.io/editor.html
-    https://jedie.github.io/pypyjs.github.io/json_test.html

At least: i didn't find a solution to focus the CodeMirror after loading ;(

EDIT: Very boring: Click on "run" button doesn't work directly after editor was focused :(

**Comment by girishramnani** [comment]
great.
this was fun

**Comment by jedie** [comment]
With https://github.com/jedie/pypyjs.github.io/commit/085d23962ca5c5e9ade80f3f7af33b7430351a55 i add a **transition-delay: 0.2s;** to fix the "hit run button"...

I will later merge this in the main repository...

**Comment by jedie** [comment]
merged with: https://github.com/pypyjs/pypyjs.github.io/pull/14

So i close this pull request.

Thanks girishramnani !

**Pull request closed without merging**
